default: &default
  adapter: postgresql
  # 追加記述
  prepared_statements: false
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "postgres" } %>

development:
  <<: *default
  database: conductor_dev

test:
  <<: *default
  database: conductor_test

production:
  <<: *default
  database: conductor_production
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  # url: <%= ENV["postgresql://postgres:conductorgM163321@db.qkovjqdrixvhmhfnyepj.supabase.co:5432/postgres"] %>
  # url: <%= ENV["postgresql://postgres.qkovjqdrixvhmhfnyepj:conductorgM163321@aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres"] %>
  url: <%= ENV["DATABASE_URL"] %>
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>