version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/rails
    ports:
      - "3001:3000"
    depends_on:
      - redis
    environment:
      - RAILS_ENV=development
      # - DATABASE_URL=postgresql://postgres:conductorgM163321@db.qkovjqdrixvhmhfnyepj.supabase.co:5432/postgres
      - DATABASE_URL=postgresql://postgres.qkovjqdrixvhmhfnyepj:conductorgM163321@aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres
      - REDIS_URL=redis://redis:6379/0
      - CORS_ORIGINS=http://localhost:3000
    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: